const validate = {
  MONTHLYINVESTMENTMIN: 500,
  MONTHLYINVESTMENTMAX: 100000,
  INVESTMENTPERIODMIN: 1,
  INVESTMENTPERIODMAX: 30,
  RATEOFRETURNMIN: 1,
  RATEOFRETURNMAX: 30,
  DELAYMIN: 1,
  DELAYMAX: 120,
}

const MONTHSINYEAR = 12
const HUNDRED = 100

module.exports = {validate, MONTHSINYEAR, HUNDRED}
